"""Add budget fields to categories table

Revision ID: 0fef7fc23783
Revises: f3a35dd8e237
Create Date: 2025-08-24 00:52:25.107429+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fef7fc23783'
down_revision = 'f3a35dd8e237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('budget_period', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('budget_period')
        batch_op.drop_column('monthly_budget')

    # ### end Alembic commands ###
